CREATE TABLE CUAHANG(
  MACH CHAR(6) PRIMARY KEY,
  TENCH VARCHAR(10),
  DCHI VARCHAR(30),
  DTHOAI INTEGER
);
  
CREATE TABLE NHANVIEN(
  MANV CHAR(3) PRIMARY KEY,
  TENNV VARCHAR(20),
  NGAYSINH DATE,
  MACH CHAR(6) REFERENCES CUAHANG(MACH)
);

CREATE TABLE HOADON(
  SOHD CHAR(6) PRIMARY KEY,
  NGAYLAP DATE DEFAULT SYSDATE,
  MANV CHAR(3)REFERENCES NHANVIEN(MANV),
  TONGTIEN INTEGER CHECK (TONGTIEN > 0)
);

CREATE TABLE HANGHOA(
  MAHANG CHAR(6) PRIMARY KEY,
  TENHANG VARCHAR(10),
  DONGIA INTEGER,
  DONVITINH VARCHAR(10)
);

CREATE TABLE CHITIETHD(
  SOHD CHAR(6) REFERENCES HOADON(SOHD),
  MAHANG CHAR(6)REFERENCES HANGHOA(MAHANG),
  SOLUONG INTEGER,
  DONGIABAN INTEGER,
  CONSTRAINT prkey PRIMARY KEY (SOHD,MAHANG)
);

INSERT INTO CUAHANG VALUES ('NK1382','NINH KIEU','13 DUONG 82 QUAN NINH KIEU', 092453646);
INSERT INTO CUAHANG VALUES ('BT3575','BINH THUY','35 DUONG 75 QUAN BINH THUY', 092439485);

INSERT INTO NHANVIEN VALUES ('001','VUONG ANH TU',to_date('01/06/12','dd/mm/yy'),'NK1382');
INSERT INTO NHANVIEN VALUES ('002','PHAN MY KIEU',to_date('04/09/97','dd/mm/yy'), 'BT3575');

INSERT INTO HOADON VALUES ('120098','','001', 24000);
INSERT INTO HOADON VALUES ('340023','','002', 202300);

INSERT INTO HANGHOA VALUES ('AO1001','AO KIEU',2000, 'DOLLAR');
INSERT INTO HANGHOA VALUES ('QUAN02','QUAN SHORT',10000, 'VND');

INSERT INTO CHITIETHD VALUES ('120098','AO1001',2, 2000);
INSERT INTO CHITIETHD VALUES ('340023','QUAN02',5, 10000);



alter table scott.cuahang add constraint ck_mach check (regexp_like(MACH,'[A-Z]\[A-Z]\d{3}'));
alter table scott.cuahang add constraint ck_dth check (regexp_like(DTHOAI,'d{4}\(-)\d{6}'));

alter table scott.nhanvien add constraint ck_manv check (regexp_like(MANV,'[A-Z]\[A-Z]\d{3}'));

alter table scott.hoadon add constraint ck_sohd check (regexp_like(sohd,'d{7}'));

alter table scott.HANGHOA add constraint ck_mahang check (regexp_like(MAHANG,'[A-Z]\d{4}'));